"""Repository hygiene — the rules .gitignore states in prose, enforced.

.gitignore is a filter, not a guard: it only ever applies to files git does not
already track. Anything added with `git add -f`, or committed before a rule
existed, stays tracked forever and no amount of ignoring undoes it. These tests
are the guard, and they run against the index (`git ls-files`) rather than the
working tree, so they see what would actually be published.

The leak guards are the sharp end. Reference checkouts and scratch images live
beside this repo while hacking on it; a pasted screenshot in the root or a photo
wallpaper is a real leak of whatever else was on screen, not a tidiness issue.
Those tests exist to fail loudly in CI before a push, so keep them strict.
"""
import subprocess
from pathlib import Path

import pytest

from conftest import theme_ids, theme_paths

IMAGE_SUFFIXES = {".png", ".jpg", ".jpeg", ".webp", ".gif", ".bmp"}


def tracked_files(repo: Path) -> list[Path]:
    out = subprocess.run(
        ["git", "ls-files", "-z"], cwd=repo, capture_output=True, text=True, check=True
    ).stdout
    return [Path(p) for p in out.split("\0") if p]


@pytest.fixture(scope="session")
def tracked(repo) -> list[Path]:
    files = tracked_files(repo)
    assert files, "git ls-files returned nothing — is this a git checkout?"
    return files


# ── NDA guards ────────────────────────────────────────────────────────────
def test_no_images_are_tracked_in_the_repo_root(tracked):
    """Pasted screenshots land here, and they leak the private project's context
    (internal GitLab, domain usernames, corporate tooling). Assets belong in
    assets/ or themes/<name>/, deliberately."""
    stray = [p for p in tracked if len(p.parts) == 1 and p.suffix.lower() in IMAGE_SUFFIXES]
    assert stray == [], (
        f"image(s) tracked in the repo root: {[str(p) for p in stray]} — "
        "move a real asset into assets/, or delete a pasted screenshot"
    )


def test_only_our_own_directories_are_tracked(tracked):
    """An allowlist, not a blocklist.

    Reference checkouts of other projects get cloned beside this one while
    hacking on it, and `git add -A` does not care whose code it is. Naming the
    trees to reject would mean naming them in a public file AND missing the next
    one; listing what HWE actually consists of catches any stray tree, whatever
    it is called. Adding a real top-level directory here is a one-line change.
    """
    ours = {
        ".github", "assets", "bin", "config", "lib", "pkg",
        "provision", "scripts", "templates", "tests", "themes",
    }
    stray = sorted({p.parts[0] for p in tracked if len(p.parts) > 1} - ours)
    assert stray == [], (
        f"tracked top-level director{'y' if len(stray) == 1 else 'ies'} not part of HWE: {stray} — "
        "if this is genuinely ours, add it to the allowlist in this test"
    )


def test_no_photo_wallpaper_libraries_are_tracked(tracked):
    """themes/<name>/wallpapers/ holds personal, likely third-party-copyrighted
    photos. The generated themes/<name>/wallpaper.png IS ours and is tracked."""
    photos = [p for p in tracked if len(p.parts) > 2 and p.parts[0] == "themes"
              and p.parts[2] == "wallpapers"]
    assert photos == [], f"photo library tracked: {[str(p) for p in photos]}"


# ── generated files must not be tracked ───────────────────────────────────
def test_generated_config_files_are_not_tracked(repo, tracked):
    """Every path .gitignore lists under 'generated by hwe theme' is regenerated
    on each apply; tracking one guarantees a permanently dirty tree."""
    tracked_set = {str(p) for p in tracked}
    generated = [
        line.strip()
        for line in (repo / ".gitignore").read_text().splitlines()
        if line.strip().startswith("config/") and "*" not in line and not line.startswith("#")
    ]
    assert generated, "could not find the generated-config block in .gitignore"
    offenders = [g for g in generated if g in tracked_set]
    assert offenders == [], f"generated file(s) tracked: {offenders}"


def test_the_working_tree_has_no_ignored_but_tracked_files(repo):
    """The definitive check: git itself reporting a tracked file it would ignore."""
    out = subprocess.run(
        ["git", "ls-files", "-i", "-c", "--exclude-standard"],
        cwd=repo, capture_output=True, text=True, check=True,
    ).stdout.split()
    assert out == [], f"tracked despite being ignored: {out}"


def test_no_python_bytecode_is_tracked(tracked):
    assert [str(p) for p in tracked if p.suffix == ".pyc" or "__pycache__" in p.parts] == []


# ── the theme tree's shape ────────────────────────────────────────────────
def test_themes_exist():
    assert theme_paths(), "no themes found"


@pytest.mark.parametrize("theme_path", theme_paths(), ids=theme_ids())
def test_every_theme_ships_its_generated_assets(theme_path):
    """A fresh clone must never have to generate anything: the wallpaper and the
    picker's preview card are committed."""
    for asset in ("wallpaper.png", "preview.png"):
        path = theme_path.parent / asset
        assert path.is_file(), f"{theme_path.parent.name}: missing {asset} (run `just walls` / `just previews`)"
        assert path.stat().st_size > 0, f"{theme_path.parent.name}: {asset} is empty"


@pytest.mark.parametrize("theme_path", theme_paths(), ids=theme_ids())
def test_every_theme_asset_is_a_real_png(theme_path):
    for asset in ("wallpaper.png", "preview.png"):
        blob = (theme_path.parent / asset).read_bytes()
        assert blob[:8] == b"\x89PNG\r\n\x1a\n", f"{theme_path.parent.name}/{asset} is not a PNG"


# ── the package lists ─────────────────────────────────────────────────────
@pytest.mark.parametrize("lst", ["core.lst", "dev.lst", "vm.lst", "aur.lst"])
def test_package_lists_hold_one_package_per_line(repo, lst):
    """guest-install.sh strips comments and takes the rest verbatim — a stray
    space would make pacman look for a package that cannot exist."""
    path = repo / "pkg" / lst
    assert path.is_file(), f"pkg/{lst} is missing — guest-install.sh reads it"
    for lineno, line in enumerate(path.read_text().splitlines(), 1):
        pkg = line.split("#")[0].strip()
        if not pkg:
            continue
        assert " " not in pkg, f"pkg/{lst}:{lineno}: '{pkg}' has a space in it"


def test_the_quality_toolchain_is_installed_by_hwe_install(repo):
    """`hwe install` installs core.lst + dev.lst. Every tool the pipeline runs
    must be in one of them, or a contributor cannot reproduce CI locally."""
    declared = set()
    for lst in ("core.lst", "dev.lst"):
        for line in (repo / "pkg" / lst).read_text().splitlines():
            pkg = line.split("#")[0].strip()
            if pkg:
                declared.add(pkg)
    required = {
        "shellcheck", "shfmt", "bats", "bats-assert", "bats-support",
        "ruff", "python-pytest", "actionlint", "yamllint",
        "python-jinja", "python-numpy", "imagemagick", "just",
    }
    missing = required - declared
    assert missing == set(), f"quality tools not installed by `hwe install`: {sorted(missing)}"


# ── executables ───────────────────────────────────────────────────────────
def test_the_cli_is_executable(repo):
    import os

    assert os.access(repo / "bin" / "hwe", os.X_OK), "bin/hwe is not executable"


@pytest.mark.parametrize("lib", sorted(p.name for p in (Path(__file__).parent.parent / "lib").glob("*.sh")))
def test_library_modules_are_sourced_not_run(repo, lib):
    """lib/*.sh define functions and rely on their caller's HWE_ROOT; an exec bit
    invites running one directly, which cannot work."""
    import os

    path = repo / "lib" / lib
    assert not os.access(path, os.X_OK), f"lib/{lib} is executable but is meant to be sourced"


@pytest.mark.parametrize("script", ["genwall.py", "genpreview.py", "render-theme.py", "wbstat.py"])
def test_python_scripts_declare_an_interpreter(repo, script):
    """wbstat.py is exec'd by waybar by path — a missing shebang breaks the bar."""
    first = (repo / "scripts" / script).read_text().splitlines()[0]
    assert first == "#!/usr/bin/env python3", f"scripts/{script}: bad shebang {first!r}"
