#!/usr/bin/env bash
# lib/keys.sh — `hwe keys`: a themed, read-only keybind cheatsheet (SUPER+/).
#
# The list is GENERATED from config/hypr/keybindings.conf so it can never drift
# from the real binds. An awk pass turns each `bind` line into a "MOD + KEY  ->
# description" row, collapses the noisy numeric/arrow blocks into one summary
# line each, and skips media/mouse binds that live on dedicated keys.
#
# Sourced by bin/hwe; relies on lib/common.sh helpers.

keys_main() {
    case "${1:-}" in
        help|-h|--help)
            printf 'usage: hwe keys\n  Keybind cheatsheet overlay (rofi; SUPER+/).\n' >&2
            return 0 ;;
    esac
    # toggle: a second press closes the sheet
    if pgrep -x rofi >/dev/null 2>&1; then pkill -x rofi; return 0; fi
    need rofi rofi-wayland || return 1

    local conf="$HWE_ROOT/config/hypr/keybindings.conf"
    local rasi="$HWE_ROOT/config/rofi/keys.rasi" # generated by `hwe theme`
    [[ -f "$conf" ]] || { err "keybindings.conf not found: $conf"; return 1; }

    local -a args=(-dmenu -i -p "" -mesg "" -no-custom -theme-str 'entry { enabled: false; }')
    [[ -f "$rasi" ]] && args+=(-theme "$rasi")

    # Read-only: rofi is just the viewer; we ignore whatever is "selected".
    _keys_render "$conf" | rofi "${args[@]}" >/dev/null 2>&1 || true
    return 0
}

# Parse keybindings.conf into aligned "MOD + KEY   description" rows.
_keys_render() {
    awk '
    function trim(s) { gsub(/^[ \t]+|[ \t]+$/, "", s); return s }

    # "$mainMod SHIFT" -> "SUPER + SHIFT"; "" -> ""
    function fmtmods(m) {
        gsub(/\$mainMod/, "SUPER", m)
        m = trim(m)
        gsub(/[ \t]+/, " + ", m)
        return m
    }

    function prettykey(k) {
        if (k == "SPACE")  return "Space"
        if (k == "Escape") return "Esc"
        if (k == "Print")  return "Print"
        if (k == "slash")  return "/"
        if (k == "mouse:272") return "LMB"
        if (k == "mouse:273") return "RMB"
        if (k == "mouse_down") return "Wheel down"
        if (k == "mouse_up")   return "Wheel up"
        return k
    }

    # Fallback description from the dispatcher when a line has no # comment.
    function dispdesc(d) {
        if (d == "killactive")             return "Close window"
        if (d == "togglefloating")         return "Toggle floating"
        if (d == "fullscreen")             return "Fullscreen"
        if (d == "pseudo")                 return "Pseudo-tile"
        if (d == "exit")                   return "Exit Hyprland session"
        if (d == "togglespecialworkspace") return "Toggle scratchpad"
        return d
    }

    # Buffer the section header and only print it once a row lands under it,
    # so sections that are entirely skipped (media/volume) leave no empty title.
    function emit(label, desc) {
        if (pending != "") { printf "\n  %s\n", pending; pending = "" }
        printf "  %-22s  %s\n", label, desc
    }

    # section header:  # --- Name ------
    /^#[ \t]*-+/ {
        h = $0
        sub(/^#[ \t]*-+[ \t]*/, "", h)
        sub(/[ \t]*-+[ \t]*$/, "", h)
        h = trim(h)
        if (h != "") pending = toupper(h)
        next
    }

    /^bind/ {
        line = $0

        # split off an inline "# comment" (kept as the human description)
        desc = ""
        hi = index(line, "#")
        if (hi > 0) { desc = trim(substr(line, hi + 1)); line = substr(line, 1, hi - 1) }
        # tidy the comment: drop parentheticals / trailing notes
        sub(/[ \t]*\(.*$/, "", desc)
        sub(/[ \t]*;.*$/,  "", desc)
        desc = trim(desc)

        # everything after the first "="  ->  mods, key, dispatcher, rest...
        eq = index(line, "=")
        if (eq == 0) next
        rhs = substr(line, eq + 1)
        n = split(rhs, f, ",")
        for (i = 1; i <= n; i++) f[i] = trim(f[i])
        mods = f[1]; key = f[2]; disp = f[3]

        # skip media/volume/brightness (dedicated keys, shown by the OSD)
        if (key ~ /^XF86/) next

        # collapse noisy repeated blocks into ONE summary row each
        if (disp == "workspace" && key ~ /^[0-9]$/) {
            if (!seen_ws)  { seen_ws = 1;  emit("SUPER + 1…0", "Switch to workspace") }
            next
        }
        if (disp == "movetoworkspace" && key ~ /^[0-9]$/) {
            if (!seen_mws) { seen_mws = 1; emit("SUPER + SHIFT + 1…0", "Move window to workspace") }
            next
        }
        if (disp == "movefocus") {
            if (!seen_focus) { seen_focus = 1; emit("SUPER + ← ↑ ↓ →", "Move focus") }
            next
        }
        if (disp == "movewindow" && mods ~ /SHIFT/) {
            if (!seen_movewin) { seen_movewin = 1; emit("SUPER + SHIFT + ← ↑ ↓ →", "Move window") }
            next
        }

        label = fmtmods(mods)
        pk = prettykey(key)
        label = (label == "") ? pk : label " + " pk

        if (desc == "") desc = dispdesc(disp)
        emit(label, desc)
    }
    ' "$1"
}
