#!/usr/bin/env bash
# lib/power.sh — `hwe power`: themed rofi session menu (lock/logout/suspend/reboot/shutdown).
# Uses rofi (already shipped), not wlogout (AUR-only on vanilla Arch); recoloured per active theme.
#
# Sourced by bin/hwe; relies on lib/common.sh helpers.

power_main() {
    case "${1:-}" in
        help|-h|--help)
            printf 'usage: hwe power\n  Themed session menu (lock/logout/suspend/reboot/shutdown) via rofi.\n' >&2
            return 0 ;;
    esac
    # toggle: a second press closes the menu
    if pgrep -x rofi >/dev/null 2>&1; then pkill -x rofi; return 0; fi
    need rofi rofi-wayland || return 1

    local rasi="$HWE_ROOT/config/rofi/powermenu.rasi"   # generated by `hwe theme`
    local -a opts=("Lock" "Logout" "Suspend" "Reboot" "Shutdown")
    local -a args=(-dmenu -i -p "" -mesg "Session" -no-custom)
    [[ -f "$rasi" ]] && args+=(-theme "$rasi")

    local choice
    choice="$(printf '%s\n' "${opts[@]}" | rofi "${args[@]}")" || return 0
    case "$choice" in
        Lock)     hyprlock ;;
        Logout)   _power_logout ;;
        Suspend)  systemctl suspend ;;
        Reboot)   systemctl reboot ;;
        Shutdown) systemctl poweroff ;;
        *)        return 0 ;;
    esac
}

# Leave the session cleanly: prefer uwsm (tears down the systemd user session)
# when it launched us; else Hyprland's own dispatcher.
_power_logout() {
    if command -v uwsm >/dev/null 2>&1 && uwsm check is-active >/dev/null 2>&1; then
        uwsm stop
    else
        hyprctl dispatch exit
    fi
}
